#ifndef _SCENE_MSG_IDS_H
#define _SCENE_MSG_IDS_H

#define REMOVE_MONSTER_MSG 1
#define SET_MONSTER_NUM_ON_BATTLE_MSG 2
#define SET_MONSTER_TYPES_ON_BATTLE_MSG 3
#define KILL_MONSTER_MSG 4
#define KILL_HERO_MSG 5
#define KILL_RIVAL_MSG 6

#endif 